CREATE TABLE PROFESOR(
    DNI VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DIRECCION VARCHAR(40) NOT NULL,
    CUENTA VARCHAR(24) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI)
);
CREATE TABLE CICLOFORM(
    CODCICLO NUMBER(3) NOT NULL,
    NOMBRE VARCHAR (30) NOT NULL,
    TIPO VARCHAR (20) NOT NULL,
    
    CONSTRAINT PK_CICLOFORM PRIMARY KEY(CODCICLO)
);
CREATE TABLE ASIGNATURA(
    CODASIG NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    NUMHORAS NUMBER(4) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    CODCICLO NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY(CODASIG),
    CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI) REFERENCES PROFESOR(DNI),
    CONSTRAINT FK_CICLOFORM FOREIGN KEY(CODCICLO) REFERENCES CICLOFORM(CODCICLO)
);
CREATE TABLE  IDIOMA(
    CODIDIOMA NUMBER(3) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    
    CONSTRAINT PK_IDIOMA PRIMARY KEY(CODIDIOMA)
);
CREATE TABLE ALUMNO(
    DNI VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DIRECCION VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CODIDIOMA NUMBER(3),
    
    CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI)
);
CREATE TABLE MATRICULA(
    DNI VARCHAR(9),
    CODASIG NUMBER(3),
    
    CONSTRAINT PK_MATRICULA PRIMARY KEY(DNI,CODASIG),
    CONSTRAINT FK_MATRICULA FOREIGN KEY(DNI) REFERENCES ALUMNO(DNI),
    CONSTRAINT FK_MATRICULA2 FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG)
);
CREATE TABLE  IDIOMASPROF(
    CODIDIOMA NUMBER(3) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    
    CONSTRAINT PK_IDIOMASPROF PRIMARY KEY(DNI, CODIDIOMA),
    CONSTRAINT FK_IDIOMASPROF1 FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA),
    CONSTRAINT FK_IDIOMASPROF2 FOREIGN KEY(DNI) REFERENCES PROFESOR(DNI)
);