CREATE TABLE DIRECTOR(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(30) NOT NULL,
    AP1 VARCHAR(30) NOT NULL,
    AP2 VARCHAR(30),
    DOMICILIO VARCHAR (30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    EMAIL VARCHAR(50),
    
    CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI)
);
CREATE TABLE SUPERMERCADO(
    CODSUP NUMBER(3),
    DIRECCION VARCHAR(30) NOT NULL,
    SUPERFICIE NUMBER(4)NOT NULL,
    ESALQUILER CHAR(1) NOT NULL,
    FECHA DATE,
    DNI VARCHAR(9),
    
    CONSTRAINT PK_SUPERMERCADO PRIMARY KEY (CODSUP),
    CONSTRAINT FK_SUPERMERCADO FOREIGN KEY (DNI) REFERENCES DIRECTOR(DNI),
    CONSTRAINT CK_SUPERMERCADO CHECK(SUPERFICIE > 0 AND ESALQUILER IN('S','s','N','n'))
);
CREATE TABLE VENDEDOR(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(30) NOT NULL,
    AP1 VARCHAR(30) NOT NULL,
    AP2 VARCHAR(30),
    DOMICILIO VARCHAR (30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    EMAIL VARCHAR(50),
    CODSUP NUMBER(3),
    
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (DNI),
    CONSTRAINT FK_VENDEDOR FOREIGN KEY (CODSUP) REFERENCES SUPERMERCADO(CODSUP) ON DELETE CASCADE
);
CREATE TABLE CLIENTE(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(30) NOT NULL,
    AP1 VARCHAR(30) NOT NULL,
    AP2 VARCHAR(30),
    DOMICILIO VARCHAR (30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    EMAIL VARCHAR(50),
    
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);
CREATE TABLE VENTA(
    CODVENTA NUMBER(3),
    FECHA DATE,
    DNI_VEN VARCHAR(9),
    DNI_CL VARCHAR(9),
    
    CONSTRAINT PK_VENTA PRIMARY KEY (CODVENTA),
    CONSTRAINT FK_VENTA_VEN FOREIGN KEY (DNI_VEN) REFERENCES VENDEDOR(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_VENTA_CL FOREIGN KEY (DNI_CL) REFERENCES CLIENTE(DNI) ON DELETE CASCADE
);
CREATE TABLE FAMILIA(
    CODFAMILIA NUMBER(3),
    
    CONSTRAINT PK_FAMILIA PRIMARY KEY (CODFAMILIA)
);
CREATE TABLE GENERO(
    CODGENERO NUMBER(3),
    
    CONSTRAINT PK_GENERO PRIMARY KEY (CODGENERO)
);
CREATE TABLE PRODUCTO(
    CODPRODUCTO NUMBER(3),
    DESCRICION VARCHAR(50)NOT NULL,
    DESCUENTO NUMBER (4,2),
    IVA NUMBER(2) NOT NULL,
    CODFAMILIA NUMBER(3),
    CODGENERO NUMBER(3),
    
    CONSTRAINT PF_PRODUCTO PRIMARY KEY (CODPRODUCTO),
    CONSTRAINT FK_PRODUCTO_FAM FOREIGN KEY (CODFAMILIA) REFERENCES FAMILIA(CODFAMILIA),
    CONSTRAINT FK_PRODUCTO_GENERO FOREIGN KEY (CODGENERO) REFERENCES GENERO(CODGENERO)
);
CREATE TABLE LINEAVENTA(
    NUMLINEA NUMBER(3),
    CODVENTA NUMBER(3),
    
    CONSTRAINT PK_LINEAVENTA PRIMARY KEY (NUMLINEA, CODVENTA),
    CONSTRAINT FK_LINEAVENTA FOREIGN KEY (CODVENTA) REFERENCES VENTA(CODVENTA)
    
);

CREATE TABLE DEVOLUCION(
    FECHA DATE,
    ESTADO VARCHAR(30) NOT NULL,
    TIPODEV VARCHAR(30) NOT NULL,
    CODVENTA NUMBER(3),
    NUMLINEA NUMBER(3),
    
    CONSTRAINT PK_DEVOLUCION PRIMARY KEY(FECHA, CODVENTA, NUMLINEA),
    CONSTRAINT FK_DEVOLUCION FOREIGN KEY(CODVENTA, NUMLINEA) REFERENCES LINEAVENTA(CODVENTA, NUMLINEA)
);
CREATE TABLE PRECIO(
    FECHA DATE,
    CODPRODUCTO NUMBER(3),
    
    CONSTRAINT PK_PRECIO PRIMARY KEY (FECHA, CODPRODUCTO),
    CONSTRAINT FK_PRECIO FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);

/*A*/
ALTER TABLE DIRECTOR ADD CONSTRAINT UQ_TELEFONO UNIQUE(TELEFONO);
ALTER TABLE DIRECTOR ADD CONSTRAINT UQ_EMAIL UNIQUE(EMAIL);

ALTER TABLE VENDEDOR ADD CONSTRAINT UQ_TELEFONO_VENDEDOR UNIQUE(TELEFONO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UQ_EMAIL_VENDEDOR UNIQUE(EMAIL);

ALTER TABLE CLIENTE ADD CONSTRAINT UQ_TELEFONO_CLIENTE UNIQUE(TELEFONO);
ALTER TABLE CLIENTE ADD CONSTRAINT UQ_EMAIL_CLIENTE UNIQUE(EMAIL);

/*EL "B" YA LO TENIA HECHO*/
ALTER TABLE DIRECTOR ADD CONSTRAINT CK_TELEFONO_DIRECTOR CHECK(LENGTH(TELEFONO) = 9);
ALTER TABLE VENDEDOR ADD CONSTRAINT CK_TELEFONO_VENDEDOR CHECK(LENGTH(TELEFONO) = 9);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_TELEFONO_CLIENTE CHECK(LENGTH(TELEFONO) = 9);

/*C*/
ALTER TABLE VENTA ADD CONSTRAINT CK_DNI_DIFERENTES CHECK(DNI_VEN <> DNI_CL);

/*D*/
ALTER TABLE PRODUCTO ADD CONSTRAINT UQ_DESCRIPCION_PRODUCTO UNIQUE(DESCRIPCION);
/*LAS FOREIGN KEY SE MODIFICA EN LOS AJUSTES DE LA TABLA,
LUEGO VAS A RESTRICCIONES Y HACES CLICK EN EL LAPIZ Y LUEGO EN LA RESTRICCION QUE QUIERES MODIFICAR, 
VAS A RESTICCIONES Y CAMBIAS AL SUPRIMIR*/