CREATE TABLE COMERCIAL(
    DNICOM VARCHAR(9),
    COMISION NUMBER(3) NOT NULL,
    CODOFOCINA NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_COMERCIAL PRIMARY KEY (DNICOM),
    CONSTRAINT CK_COMISION CHECK(COMISION >0 AND COMISION <100)
);
CREATE TABLE VENDEDOR(
    DNI VARCHAR(9),
    TURNO VARCHAR(6) NOT NULL,
    CODOFOCINA NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (DNI),
    CONSTRAINT FK_OFICINA FOREIGN KEY (CODOFICINA) REFERENCES OFICINA(CODOFICINA) ON DELETE CASCADE,
    CONSTRAINT CK_TURNO CHECK (TURNO IN ('MAÑANA', 'TARDE', 'NOCHE'))
);
CREATE TABLE OFCINA(
    CODOFICINA NUMBER (3),
    DIRECCION VARCHAR (40) NOT NULL,
    TELEFONO NUMBER (9) NOT NULL,
    DNICOM VARCHAR (9) NOT NULL,
    
    CONSTRAINT PK_OFICINA PRIMARY KEY (CODOFICINA),
    CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI) REFERENCES DIRECTOR(DNI)ON DELETE CASCADE,
    CONSTRAINT CK_OFICINA CHECK (LENGTH(TELEFONO) =9),
);

ALTER TABBLE OFICINA  ADD CONSTRAINT FK_COMERCIAL FOREIGN KEY (DNICOM) REFERENCES COMERCIAL(DNICOM)ON DELETE CASCADE;
ALTER TABLE COMERCIAL ADD CONSTRAINT FK_OFICINA FOREIGN KEY (CODOFICINA) REFERENCES OFICINA(CODOFICINA) ON DELETE CASCADE;